
synplify.prj:
	synplify -batch synplify_project.tcl

synplify_115b_ddr: synplify.prj
	synplify -batch synplify.prj -impl rev_1_15b_ddr

synplify_115d_bram: synplify.prj
	synplify -batch synplify.prj -impl rev_1_15d_bram

synplify_115d_ddr: synplify.prj
	synplify -batch synplify.prj -impl rev_1_15d_ddr

