#ifndef FX2EMULATIONDEBUGCONNECTOR_H_
#define FX2EMULATIONDEBUGCONNECTOR_H_

// For use in Modelsim at the moment

#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <fcntl.h>
#include <arpa/inet.h>
#include <stdio.h>

#include <systemc.h>

#include <queue>

/*
 * TODO:
 *  - Change fx2 clock to be generated by the module
 */

SC_MODULE(FX2EmulationDebugConnector)
{
    sc_in<bool> fx2_ifclk;
    sc_out<bool> fx2_flaga;
    sc_out<bool> fx2_flagb;
    sc_out<bool> fx2_flagc;
    sc_out<bool> fx2_flagd;
    sc_in<bool> fx2_sloe;
    sc_in<bool> fx2_slrd;
    sc_in<bool> fx2_slwr;
    sc_in<bool> fx2_pktend;
    sc_in<sc_bv<2> > fx2_fifoadr;
    sc_inout<sc_lv<16> > fx2_fd;
    sc_out<bool> reset;

    bool in_reset;
    std::queue<uint16_t> input_queue;
    std::queue<uint16_t> output_queue;

    SC_CTOR(FX2EmulationDebugConnector)
    {
        SC_THREAD(handler);
        SC_THREAD(ctrlhandler);
        SC_METHOD(interface);
        sensitive << fx2_ifclk.posedge_event();
        SC_METHOD(drivefd);
        sensitive << fx2_sloe;
        in_reset = true;
    }

    void drivefd();
    void interface();
    void handler();
    void ctrlhandler();
};

#endif
