// Automatically generated by traceeventgen, do not change here

case 512: if (ofevents) fprintf(ofevents,"[%16s] Tick occured\n",sc_time_stamp().to_string().c_str()); break;
case 513: if (ofevents) fprintf(ofevents,"[%16s] Create thread for function: %p\n",sc_time_stamp().to_string().c_str(),reinterpret_cast<void*>(val)); break;
case 514: if (ofevents) fprintf(ofevents,"[%16s] Created thread with thread id: %p\n",sc_time_stamp().to_string().c_str(),reinterpret_cast<void*>(val)); break;
case 515: if (ofevents) fprintf(ofevents,"[%16s] Add to scheduler queue: %p\n",sc_time_stamp().to_string().c_str(),reinterpret_cast<void*>(val)); break;
case 516: if (ofevents) fprintf(ofevents,"[%16s]           -> thread id: %p\n",sc_time_stamp().to_string().c_str(),reinterpret_cast<void*>(val)); break;
case 517: if (ofevents) fprintf(ofevents,"[%16s] Thread started: %p\n",sc_time_stamp().to_string().c_str(),reinterpret_cast<void*>(val)); break;
case 518: if (ofevents) fprintf(ofevents,"[%16s] Thread finished: %p\n",sc_time_stamp().to_string().c_str(),reinterpret_cast<void*>(val)); break;
case 519: if (ofevents) fprintf(ofevents,"[%16s] Scheduler selects: %p\n",sc_time_stamp().to_string().c_str(),reinterpret_cast<void*>(val)); break;
case 520: if (ofevents) fprintf(ofevents,"[%16s] Thread yields\n",sc_time_stamp().to_string().c_str()); break;
case 521: if (ofevents) fprintf(ofevents,"[%16s] Thread suspends\n",sc_time_stamp().to_string().c_str()); break;
case 522: if (ofevents) fprintf(ofevents,"[%16s] Resume thread: %p\n",sc_time_stamp().to_string().c_str(),reinterpret_cast<void*>(val)); break;
case 523: if (ofevents) fprintf(ofevents,"[%16s] Wait for thread: %p\n",sc_time_stamp().to_string().c_str(),reinterpret_cast<void*>(val)); break;
case 524: if (ofevents) fprintf(ofevents,"[%16s] Exit thread: %p\n",sc_time_stamp().to_string().c_str(),reinterpret_cast<void*>(val)); break;
case 525: if (ofevents) fprintf(ofevents,"[%16s] Signal waiting thread: %p\n",sc_time_stamp().to_string().c_str(),reinterpret_cast<void*>(val)); break;
