#!/bin/bash
set -e

# optimsoc-app-link <system> <application>

if [ $# -lt 2 ]; then
   echo "Usage: optimsoc-app-link <system> <application>"
   echo "  where:"
   echo "    <system> is either baremetal (or gzll in future)"
   echo "    <application> is an application, e.g. hello_simple"
   exit
fi

targetdir=$PWD/${2/\//_}.lnk
srcdir=${OPTIMSOC_APPS}/$1/$2

if [ ! -d $srcdir ]; then
    echo "Cannot find sources directory $srcdir."
    exit 1
fi

if [ -d $targetdir ]; then
    echo "Target directory $targetdir already exists."
    exit 1
fi

mkdir $targetdir

wd=$PWD
cd $srcdir

for f in `find . -type f`; do
    dirname=`dirname $f`
    [ -d $targetdir/$dirname ] || mkdir $targetdir/$dirname
    ln -s $srcdir/$f $targetdir/$f
done

cd $wd
