#!/bin/bash

# sw_copy <system> <application>

if [ $# -lt 2 ]; then
   echo "Usage: optimsoc-app-link <system> <application>"
   echo "  where:"
   echo "    <system> is either baremetal (or gzll in future)"
   echo "    <application> is an application, e.g. hello_simple"
   exit
fi

bname="`basename $2`.lnk"

if [ -d $bname ]; then
    echo "directory $bname already exists"
    exit
fi

mkdir $bname

if [ ! -d ${OPTIMSOC}/src/sw/system/apps/$1/$2 ]; then
    echo "Cannot find ${OPTIMSOC}/src/sw/system/apps/$1/$2"
    rmdir $bname
    exit
fi

for f in `find ${OPTIMSOC}/src/sw/system/apps/$1/$2 -type f`; do
    bf=`echo $f | sed 's|'${OPTIMSOC}/src/sw/system/apps/$1/$2/'||'`
    ln -s $f $bname/$bf
done
