#!/bin/bash

if [ $# -lt 2 ]; then
   echo "Usage: optimsoc-app-copy <system> <application>"
   echo "  where:"
   echo "    <system> is either dm (or sm in future)"
   echo "    <application> is an application, e.g. baremetal/hello_simple"
   exit
fi

cp -r ${OPTIMSOC_APPS}/$1/$2 .
