#!/bin/bash

# sw_copy <system> <application>

if [ $# -lt 2 ]; then
   echo "Usage: sw_copy <system> <application>"
   echo "  where:"
   echo "    <system> is either dm, pgas or sm"
   echo "    <application> is an application, e.g. baremetal/hello_simple"
   exit
fi

bname=`basename $2`

if [ -d $bname ]; then
    echo "directory $bname already exists"
    exit
fi

mkdir $bname

for f in `find ${OPTIMSOC}/src/sw/system/$1/apps/$2 -type f`; do
    bf=`echo $f | sed 's|'${OPTIMSOC}/src/sw/system/$1/apps/$2/'||'`
    ln -s $f $bname/$bf
done
