#
# FX2 Interface Constraints for use by Xilinx Vivado
#
# Board: ZTEX USB-FPGA 2.13
#

set_property PACKAGE_PIN P17 [get_ports fx2_ifclk]
set_property PACKAGE_PIN N16 [get_ports fx2_flaga_n]
set_property PACKAGE_PIN N15 [get_ports fx2_flagb_n]
set_property PACKAGE_PIN N14 [get_ports fx2_flagc_n]
set_property PACKAGE_PIN N17 [get_ports fx2_flagd_n]
set_property PACKAGE_PIN R10 [get_ports fx2_pktend_n]
set_property PACKAGE_PIN T14 [get_ports fx2_sloe_n]
set_property PACKAGE_PIN V16 [get_ports fx2_slrd_n]
set_property PACKAGE_PIN U16 [get_ports fx2_slwr_n]
set_property PACKAGE_PIN R17 [get_ports fx2_com_rst]
set_property PACKAGE_PIN R18 [get_ports fx2_logic_rst]
set_property PACKAGE_PIN V14 [get_ports {fx2_fd[15]}]
set_property PACKAGE_PIN U14 [get_ports {fx2_fd[14]}]
set_property PACKAGE_PIN U13 [get_ports {fx2_fd[13]}]
set_property PACKAGE_PIN V12 [get_ports {fx2_fd[12]}]
set_property PACKAGE_PIN V11 [get_ports {fx2_fd[11]}]
set_property PACKAGE_PIN U11 [get_ports {fx2_fd[10]}]
set_property PACKAGE_PIN V10 [get_ports {fx2_fd[9]}]
set_property PACKAGE_PIN T9 [get_ports {fx2_fd[8]}]
set_property PACKAGE_PIN R13 [get_ports {fx2_fd[7]}]
set_property PACKAGE_PIN R12 [get_ports {fx2_fd[6]}]
set_property PACKAGE_PIN M18 [get_ports {fx2_fd[5]}]
set_property PACKAGE_PIN L18 [get_ports {fx2_fd[4]}]
set_property PACKAGE_PIN M14 [get_ports {fx2_fd[3]}]
set_property PACKAGE_PIN L14 [get_ports {fx2_fd[2]}]
set_property PACKAGE_PIN L16 [get_ports {fx2_fd[1]}]
set_property PACKAGE_PIN M16 [get_ports {fx2_fd[0]}]
set_property PACKAGE_PIN T11 [get_ports {fx2_fifoadr[1]}]
set_property PACKAGE_PIN R11 [get_ports {fx2_fifoadr[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports fx2_ifclk]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fd[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fd[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fd[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fd[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fd[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fd[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fd[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fd[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fd[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fd[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fd[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fd[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fifoadr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fx2_fifoadr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports fx2_pktend_n]
set_property IOSTANDARD LVCMOS33 [get_ports fx2_sloe_n]
set_property IOSTANDARD LVCMOS33 [get_ports fx2_slrd_n]
set_property IOSTANDARD LVCMOS33 [get_ports fx2_slwr_n]
set_property IOSTANDARD LVCMOS33 [get_ports fx2_com_rst]
set_property IOSTANDARD LVCMOS33 [get_ports fx2_logic_rst]
set_property IOSTANDARD LVCMOS33 [get_ports fx2_flagd_n]
set_property IOSTANDARD LVCMOS33 [get_ports fx2_flagb_n]
set_property IOSTANDARD LVCMOS33 [get_ports fx2_flagc_n]
set_property IOSTANDARD LVCMOS33 [get_ports fx2_flaga_n]

