all:
	@echo "Run make with the following targets:"
	@echo "  build-modelsim      Build ModelSim simulation"
	@echo "  run-modelsim        Simulate the ModelSim simulation"
	@echo "  run-modelsim-nonint Simulate the ModelSim simulation (noninteractive)"

TBENCH = tb_system_2x2_cccc_diasys
TBENCH_SYSC_SRCS = glip_tcp_toplevel.cpp

include ../../Makefile.modelsim.inc

